-- JASNAL v51: 관리자 신규 가입신청 Push 알림
-- Supabase SQL Editor에서 1회 실행하세요.

create table if not exists public.admin_notification_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  signup_notifications boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.admin_notification_preferences enable row level security;

drop policy if exists "admin notification pref select own" on public.admin_notification_preferences;
create policy "admin notification pref select own"
on public.admin_notification_preferences for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "admin notification pref insert own" on public.admin_notification_preferences;
create policy "admin notification pref insert own"
on public.admin_notification_preferences for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.members m
    where m.auth_user_id = auth.uid()
      and m.role = '관리자'
      and m.status = '활동중'
  )
);

drop policy if exists "admin notification pref update own" on public.admin_notification_preferences;
create policy "admin notification pref update own"
on public.admin_notification_preferences for update
to authenticated
using (
  auth.uid() = user_id
  and exists (
    select 1 from public.members m
    where m.auth_user_id = auth.uid()
      and m.role = '관리자'
      and m.status = '활동중'
  )
)
with check (auth.uid() = user_id);

create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  type text not null,
  member_id bigint,
  member_name text,
  group_name text,
  title text not null,
  body text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

alter table public.admin_notifications enable row level security;

drop policy if exists "authenticated can queue signup notification" on public.admin_notifications;
create policy "authenticated can queue signup notification"
on public.admin_notifications for insert
to authenticated
with check (
  auth.uid() = created_by
  and type = 'signup_request'
);

drop policy if exists "admins can read admin notifications" on public.admin_notifications;
create policy "admins can read admin notifications"
on public.admin_notifications for select
to authenticated
using (
  exists (
    select 1 from public.members m
    where m.auth_user_id = auth.uid()
      and m.role = '관리자'
      and m.status = '활동중'
  )
);

-- IMPORTANT:
-- 이 SQL은 '가입신청 알림 큐'와 관리자별 수신 설정을 만듭니다.
-- 실제 휴대폰 백그라운드 Push 전송은 서버(Edge Function)가
-- admin_notifications의 미처리 행을 읽어 push_subscriptions로 보내야 합니다.
-- 브라우저에 VAPID private key/service-role key를 넣으면 안 됩니다.
